// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Swift;

  Swift = require('../lib/swift');

  module.exports = function(grunt) {
    return grunt.registerMultiTask('swift', 'do swift upload', function() {
      var done, options, targetOpts, taskOpts;
      done = this.async();
      if (!this.target) {
        throw new Error('Task require a target. IE: swift:dev, swift:prod');
      }
      taskOpts = grunt.config(['swift', 'options']) || {};
      targetOpts = grunt.config(['swift', this.target, 'options']) || {};
      options = grunt.util._.merge({}, taskOpts, targetOpts);
      if (!options.credentials) {
        throw new Error('Config options.credentials is required in Gruntfile');
      }
      return new Swift(options.credentials, grunt.log.writeln, function(swift) {
        return swift.uploadFiles(options.path, done);
      });
    });
  };

}).call(this);
