// Generated by CoffeeScript 1.12.6
(function() {
  var SwiftUpload, async, fs, glob, path, storage;

  async = require('async');

  glob = require('glob');

  storage = require('openstack-storage');

  path = require('path');

  fs = require('fs');

  process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

  SwiftUpload = (function() {
    function SwiftUpload(options, logger, cb) {
      var authFn;
      this.options = options;
      this.logger = logger || console.log;
      authFn = async.apply(storage.authenticate, this.options);
      this.service = new storage.OpenStackStorage(authFn, (function(_this) {
        return function(err, res, tokens) {
          if (err) {
            return _this.logger('[Swift Auth] ', err, ', tokens: ', tokens);
          } else {
            _this.tokens = tokens;
            _this.logger('[Swift Auth] ' + res.statusCode + ' - ' + tokens.id);
            return cb(_this);
          }
        };
      })(this));
    }

    SwiftUpload.prototype.uploadFiles = function(paths, cb) {
      var counter, i, len, p;
      if (!Array.isArray(paths)) {
        paths = [paths];
      }
      for (i = 0, len = paths.length; i < len; i++) {
        p = paths[i];
        counter = 0;
        this.uploadFile(p, function() {
          return counter += 1;
        });
      }
      return setInterval((function(_this) {
        return function() {
          if (counter === paths.length) {
            return cb();
          }
        };
      })(this), 200);
    };

    SwiftUpload.prototype.uploadFile = function(file, cb) {
      var putFileOptions, remoteName;
      remoteName = path.join(this.options.storagePath, file);
      putFileOptions = {
        remoteName: remoteName,
        localFile: file
      };
      return this.service.putFile(this.options.container, putFileOptions, (function(_this) {
        return function(err, statusCode) {
          var url;
          url = _this.tokens.storageUrl + path.join('/', _this.options.container, remoteName);
          _this.logger('[Swift upload] ' + statusCode + ' - ' + url);
          if (err) {
            _this.logger(err);
          }
          return cb();
        };
      })(this));
    };

    return SwiftUpload;

  })();

  module.exports = SwiftUpload;

}).call(this);
