// Generated by CoffeeScript 1.10.0
(function() {
  var SwiftUpload, async, fs, glob, path, storage;

  async = require('async');

  glob = require('glob');

  storage = require('openstack-storage');

  path = require('path');

  fs = require('fs');

  process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

  SwiftUpload = (function() {
    function SwiftUpload(options, logger, cb) {
      var authFn;
      this.options = options;
      this.logger = logger || console.log;
      authFn = async.apply(storage.authenticate, this.options);
      this.service = new storage.OpenStackStorage(authFn, (function(_this) {
        return function(err, res, tokens) {
          _this.tokens = tokens;
          _this.logger('[Swift Auth] ' + res.statusCode + ' - ' + tokens.id);
          return cb(_this);
        };
      })(this));
    }

    SwiftUpload.prototype.uploadFiles = function(paths, cb) {
      var i, len, p, results;
      if (!Array.isArray(paths)) {
        paths = [paths];
      }
      results = [];
      for (i = 0, len = paths.length; i < len; i++) {
        p = paths[i];
        results.push(glob(p, (function(_this) {
          return function(err, files) {
            var counter, file, j, len1;
            counter = 0;
            for (j = 0, len1 = files.length; j < len1; j++) {
              file = files[j];
              if (fs.lstatSync(file).isDirectory()) {
                continue;
              }
              _this.uploadFile(file, function() {
                return counter += 1;
              });
            }
            return setInterval(function() {
              if (counter === files.length) {
                return cb();
              }
            }, 200);
          };
        })(this)));
      }
      return results;
    };

    SwiftUpload.prototype.uploadFile = function(filename, cb) {
      var putFileOptions, remoteName;
      remoteName = path.join(this.options.storagePath, filename);
      putFileOptions = {
        remoteName: remoteName,
        localFile: filename
      };
      return this.service.putFile(this.options.container, putFileOptions, (function(_this) {
        return function(err, statusCode) {
          var url;
          url = _this.tokens.storageUrl + path.join('/', _this.options.container, remoteName);
          _this.logger('[Swift upload] ' + statusCode + ' - ' + url);
          if (err) {
            _this.logger(err);
          }
          return cb();
        };
      })(this));
    };

    return SwiftUpload;

  })();

  module.exports = SwiftUpload;

}).call(this);
